[package]
name = "sonion"
version = "0.1.0"
edition = "2024"

[dependencies]
sonion-protocol.workspace = true
sonion-server.workspace = true
tokio.workspace = true 
clap.workspace = true 
rcgen.workspace = true
rustls.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true