[package]
name = "sonion-server"
version = "0.1.0"
edition = "2024"

[dependencies]
sonion-protocol.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
mime_guess.workspace = true
thiserror.workspace = true
tracing.workspace = true
anyhow.workspace = true
rustls.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true